django_object_actions/tests/test_utils.py, django_object_actions/utils.py, example_project/polls/fixtures/sample_data.json, requirements.txt, tox.ini
The docs have
```
@takes_instance_or_queryset
def tighten_lug_nuts(self, request, queryset):
queryset.update(lugnuts=F('lugnuts') - 1)
```
but this updates all values since queryset seems to ignore the `_result_cache` (as proven by the test in my first commit). I'm not sure `filter(pk=...)` is the right way to implement this behavior, but `@takes_instance_or_queryset` seems dangerous as it is now.
=> update individual item for instance case

django_object_actions/utils.py
Removed usage of django.conf.urls.patterns, in order to avoid warning :
"""
RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
"""
=> Fixed urls patterns usage warning in Django 1.9

django_object_actions/tests/test_utils.py, django_object_actions/utils.py, requirements.txt
Fixes #45 
#43 had some code to use named url patterns for the tool view. The name for the tool was based on the admin change view's url pattern. This PR changes the code for that to construct the url based on the historical url name... %(app)_%(model)_change instead of scanning through a list of urls.
Some small refactors and doc updates as well.
=> Fix unnamed admin urls

.travis.yml, django_object_actions/utils.py, setup.py, tox.ini
re-do of #38 This allows HttpStreamingResponses for tools, not just HttpResponse
=> All http responses

README.rst
The context will _always_ have an 'original' key if coming from Django's .changeform_view(), but it will be None if a new object is being added.
Running the code as provided in the example will result in AttributeErrors when the code enters the if and tried to access attributes on a None object.
I've made the if check very cautious just in case people heavily override the ModelAdmin.changeform_view() and/or the Model.__bool__() methods.
=> Fixed example in documentation that doesn't work as advertised.

django_object_actions/tests/test_admin.py, django_object_actions/utils.py, example_project/polls/admin.py, example_project/urls.py
when used several admins, you always redirect to default `admin`, should redirect back to active admin
=> add ability redirect back active admin

django_object_actions/tests/test_admin.py, django_object_actions/utils.py, example_project/polls/admin.py, example_project/polls/factories.py, example_project/settings.py
Previously, if a user set an extra context in `change_view` or `changelist_view`, it was thrown out.
=> Fix how extra context set by admins was not passed

.travis.yml, django_object_actions/tests/__init__.py, django_object_actions/utils.py, tox.ini
closes #57 and #56 
Django 1.5 and Python 2.6 are really old at this point. The test suite has been failing in those environments and there's no reason to try and fix it when they shouldn't be supported.
This makes it so CI for future pull requests will work.
Add official Django 1.10 support
=> Remove old things

.gitignore, .travis.yml, Makefile, example_project/polls/admin.py, example_project/settings.py, example_project/urls.py, requirements.txt, tox.ini
Mostly involves updating syntax in the example project. No changes required in the `django_object_actions` app. Though I really should add an appconfig I suppose.
=> Add Django 1.10 to 'tox' support

django_object_actions/tests/test_admin.py, django_object_actions/utils.py
Originally, this was only designed to support models with numeric and uuid primary keys. But since the Django Admin supports using anything, so should this.
Closes #68 #66 #72
=> Add support for all primary key formats

requirements.txt
Tests failed with
```
ImportError: The ``fake-factory`` package is now called ``Faker``.
Please update your requirements.
```
From faker docs:
The `fake-factory` package was deprecated on December 15th, 2016.
Use the `Faker` package instead.
This commit fixes it
=> Fix faker in requirements

django_object_actions/tests/test_admin.py, django_object_actions/tests/tests.py, django_object_actions/utils.py, example_project/polls/admin.py, example_project/settings.py, requirements.txt, tox.ini
Get rid of Django 2.0 DeprecationWarning and add 1.11 tox env.
It also fixes faker dependency addressed in #76
=> Get rid of Django 2.0 DeprecationWarning

.travis.yml, Makefile, example_project/polls/migrations/0001_initial.py, example_project/polls/models.py, example_project/settings.py, example_project/urls.py, requirements.in, requirements.txt, tox.ini
Adding support for Django 2.0+, and removing support for Django versions up to 1.8, the oldest supported LTS release. This allows us to replace the now deprecated django-extensions UUIDField with the Django native version, and drop a couple of other hacks. Resolves #84
=> Add support for Django 2.0

Dockerfile, Makefile, django_object_actions/models.py, example_project/polls/models.py, example_project/settings.py, requirements.txt, setup.cfg
No code changes, just:
* upgrade dev dependencies
* unify django version specific code comments to be `DJANGO<version>`
* update workflows to use more modern versions
* `make build`
* `make run`
* Browse to localhost:8000/admin/
* login with `admin`/`admin`
=> Cleanup random Django version support docs

django_object_actions/templates/django_object_actions/change_form.html, django_object_actions/templates/django_object_actions/change_list.html
If you want to filter change_list by some conditions, then open each object and run some object action there, you will be returned to change_list with the same preserved filters.
Fix #83
=> Return to preserved filters on change_list after object action

django_object_actions/utils.py
With this change the default label changes from `some_action` to `Some action`
=> Make default labels prettier

Makefile, django_object_actions/templates/django_object_actions/change_list.html, django_object_actions/tests/test_urls.py, requirements.txt
I probably copy pasted something wrong and brought an extra arg into the `reverse`, so `reverse` never found anything and the actions in the changelist never rendered with a `href`. This makes the args match the url definition so these buttons work again.
Thanks to @mvbrn for the original fix.
closes #96
=> fix: changelist action links had no 'href'

.travis.yml, Makefile, django_object_actions/tests/test_admin.py, django_object_actions/tests/test_utils.py, django_object_actions/utils.py, example_project/polls/admin.py, example_project/polls/models.py, requirements.in, setup.py, tox.ini
BREAKING CHANGE: This release drops Python 2 support
Django has [dropped Python 2 support](https://docs.djangoproject.com/en/2.2/releases/2.0/#python-compatibility) ever since Django 2.0 (December 2, 2017). With Django 3.0 coming very soon and Python 2 reaching end of life, it doesn't make sense to continue supporting Python 2.
=> feat: Drop Python 2 support

.travis.yml, Makefile, README.md, tox.ini
Django 3.0 is out: https://docs.djangoproject.com/en/3.0/releases/3.0/ Let's see if we're compatible. It turns out no code changes are needed huzzah!
=> feat: add Django 3 test support

.travis.yml, setup.py, tox.ini
BREAKING CHANGE: drop Python 3.4 support in preparation for adding type hints and Django 3.1 support
Prereq for #107
=> feat(deps): Drop Python 3.4 support

django_object_actions/utils.py
Use `django.urls.re_path()` when available, instead of the deprecated `django.conf.urls.url()`.
* `re_path()` is available since Django 2.0.
* `url()` will be removed in Django 4.0.
=> use django.urls.re_path when available

.travis.yml, django_object_actions/tests/test_admin.py, example_project/polls/factories.py, example_project/settings.py, requirements.txt, tox.ini
https://docs.djangoproject.com/en/3.2/releases/3.2/
I really need to drop support for old versions now. Lots of deps are starting to step on each other and drop things. Django itself doesn't support Django 3.0 anymore with the release of Django 3.2
=> chore: add Django 3.2 to test grid

.github/workflows/conventional-pr.yml, .github/workflows/release.yml, pyproject.toml
I'll switch it to be automated on push to `master` at some point.
=> feat(ci): add manual semantic-release

pyproject.toml
Fix "error: [Errno 2] No such file or directory: 'django-object-actions/__init__.py'" error when creating a release
=> fix: fix typo in version_variable

.github/workflows/ci.yml, .github/workflows/conventional-pr.yml, .github/workflows/release.yml, poetry.lock, pyproject.toml
BREAKING CHANGE: Python 3.6 is past end-of-life and is no longer supported. Keeping it in `pyproject.toml` was causing pains trying to install packages. Let's drop it while we're dropping support for other old stuff.
=> feat!: drop Python 3.6 support

README.md, django_object_actions/__init__.py, django_object_actions/tests/test_utils.py, django_object_actions/utils.py, example_project/polls/admin.py
Add an `@action` decorator that behave's like Django's `admin.action` decorator[^1] to clean up customizing object actions.
[closes #115](https://github.com/crccheck/django-object-actions/issues/115)
Also relates to #107
[^1]: https://docs.djangoproject.com/en/stable/ref/contrib/admin/actions/#django.contrib.admin.action
=> feat: provide action decorator to pass label, description and atts to the admin method 

.github/workflows/ci.yml, .github/workflows/release.yml
Hopefully this fixes the broken GitHub Action too https://github.com/crccheck/django-object-actions/actions/runs/3464471740
`error: No module named 'packaging'`
https://github.com/python-semantic-release/python-semantic-release/issues/489
closes #144
=> chore(ci): upgrade python-semantic-release

.github/workflows/ci.yml
fixes deprecation warnings in CI:
> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> chore(ci): remove deprecated set-output syntax

README.md, django_object_actions/utils.py
To reduce future diffs from autoformat
=> docs: update README style

pyproject.toml
I missed some updated config changes
- https://python-semantic-release.readthedocs.io/en/latest/migrating_from_v7.html#version-toml
- https://python-semantic-release.readthedocs.io/en/latest/configuration.html#config-version-variables
=> fix(ci): update [tool.semantic_release] names

.github/workflows/ci.yml
https://docs.djangoproject.com/en/5.0/releases/5.0/
=> chore: add Django v5 to CI matrix

django_object_actions/templates/django_object_actions/action_trigger.html, django_object_actions/templates/django_object_actions/change_form.html, django_object_actions/templates/django_object_actions/change_list.html, django_object_actions/utils.py
Another try at enforcing POST actions. This change is more gradual than #149 - when library user doesn't change default options the behavior is exactly the same as before the change, that is:
1. Action buttons send GET requests
2. Action handlers accept GET and POST requests
However, user can change this behavior using `methods` and `button_type` kwargs. For example `@action(methods=['POST'], button_type='form')` results in
1. Action button sends POST requests
2. Action handler accepts only POST request
Unfortunately I have this tested only within my project. Also the docs are missing.
And one more thing - I think it is better to use `<input type="submit">` instead of js to submit the form. This js is need to make the buttons look the same in both versions. With proper CSS (that is beyond …
=> wip to select GET or POST for actions

.github/workflows/release.yml
There have been a lot of releases since v8.0.8 https://github.com/python-semantic-release/python-semantic-release/blob/master/CHANGELOG.md#v808-2023-08-26
The breaking change was dropping Python 3.7. While this project supports 3.7... that will change the next opportunity
=> chore(ci): upgrade python-semantic-release to v9.8.8

.github/workflows/ci.yml, Dockerfile, django_object_actions/tests/test_utils.py, poetry.lock, pyproject.toml
Python 3.7 hasn't been supported in ages, and it's causing errors on CI actions so let's just drop it.
It appears that [dropping Python 3.7 is desired anyway](https://github.com/crccheck/django-object-actions/blob/master/CHANGELOG.md#v430-2024-09-10)!
=> chore!: drop long-unsupported py3.7 py3.8 django versions

.dockerignore, .github/workflows/release.yml, django_object_actions/__init__.py
Unable to resolve action `python-semantic-release/upload-to-gh-release@9.21.0`, unable to find version `9.21.0`
It is now named `python-semantic-release/publish-action`
=> fix(ci): Fix release should use python-semantic-release/publish-action
